# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InstagramChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InstagramChallenge
	pod 'Tabman', '~> 2.9'
	pod 'SnapKit', '~> 5.0.0'
	pod 'Alamofire'
	pod 'KeychainSwift', '~> 20.0'
	pod 'Kingfisher', '~> 7.3.0'

end
